# Taken from https://github.com/itzmeanjan/ml-kem/blob/61cf680b1c0e2590bd7b650c07cd477e90cab46d/.github/workflows/test_ci.yml
name: Test Ascon LwC Cipher Suite (NIST SP 800-232)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]
        build_type: [debug, release]
        test_type: [standard, asan, ubsan]
      max-parallel: 4

    steps:
      - uses: actions/checkout@v4

      - name: Setup Google Test
        uses: Bacondish2023/setup-googletest@v1
        with:
          tag: v1.15.2

      - name: Build and Test (${{ matrix.compiler }}, ${{ matrix.build_type }}, ${{ matrix.test_type }})
        run: |
          CXX=${{ matrix.compiler }}
          if [[ ${{ matrix.test_type }} == "standard" ]]; then
            make test -j
          else
            make ${{ matrix.build_type }}_${{ matrix.test_type }}_test -j
          fi

      - name: Run Examples
        if: ${{ matrix.test_type == 'standard' && matrix.build_type == 'release' }}
        run: |
          CXX=${{ matrix.compiler }} make example -j
